service: codecommit-buddybuild-integration

custom:
  env:
    APP_ID: ${env:APP_ID}
    ACCESS_TOKEN: ${env:ACCESS_TOKEN}

provider:
  name: aws
  region: ${env:AWS_REGION}
  runtime: nodejs6.10

functions:
  launchBuild:
    handler: handler.launchBuild